openapi: 3.0.3
info:
  title: Sensedia Energy API
  description: API para gestão de faturas e serviços de energia elétrica
  version: 1.0.0
tags:
  - name: Regra de Negócio
    externalDocs:
      description: Documentação
      url: https://docs.google.com/document/d/1BKY7FFuiM0_929unEMPbzIEqIr6nMPjOJkxZU4yXBGg/edit?usp=sharing
  - name: Microserviços
    description: Java e funções SAP
    externalDocs:
      description: Fluxo Webservice
      url: https://mermaid.live/view#pako:eNqdVU1P20AQ_SujvQBSgmyTJiFIrZyYUFoIAVq-EoQWexNWjXejtY34MD-m7aHqubde88c6XiesSQlIXKJ4M-_NzHtvnXviy4CRBhkqOr6CL95GX_RFlFzmz33SHiU3sgEtxamCjrym0KZxomif9AWA22uNOBMxO4dy-X16KEfc5zGd_Jr8lDCmioKvgSIDDjQwhWbP7W6fb2T4poZ1qZr8CFmsZATXk-8jHsjoQwqt5WVYWcnKWjk7D1PwMrBmLZLmbJ4uc2PFLxMOSQgiCZmSF7PGm5qwUOqxARcMohgLIvBlKGEpow7oUgrt-eoDFkslcKXJn4APJQQMFIvGEuGw5Fg2YrYMZktjdvFXVOHJIPDY0TT7aID5sh1UMIXt3otNK5a1lK--XewWMhHRIQuzYqYULjV1CQbIxXzUFya_gYup2Nj_06w_E8Fz_u9dxkyBx2I6umIRBE9j8PnVGEiNDwr4mSk7Jg07Gt2einTDo5hhDHaNNLsmBx2dAzVV53_inLGz0IQSXNORVCWERuhCPirDTIXsws-XSWFvvnXuStccd_WxmPzNqGfhxaH3n4yXm1CxKlCe6gZC9xO-FDgaRiCfd_9lGxdgUzh4xb6ukj6LIryJXTqkSBzrJBU9_Pqqh-NHknGRJAmNmUfGzKNnzTw20h0bM096JlmswP74MsgpTwziVOs7m6gAwUsMUZKdyhx0mr8UCm4UdUUNB1yF-ZopnJnxzhZZMQdxXYM5KYTEbT4bARsjYDzQTtIES_gdxYuYj-w2X47BYjy2bc0rPB3He1siXe-NkXQ3C5kkJYIXJKQ8wL-a-4y3T-IrFrI-aeDXgKpvWQofsC7b5vBW-KQRq4SVSDIOaMw8TjHS4exwTMWZlMVH0rgnN6RRfmdZq_V6re7YVcdat516tURuSWPdXl13LGfNqeFnfa3mPJTInWawVytO1a5U7Mq7WrVSdZyHf176ZOw
  - name: Banco de Dados
    description: Queries e funções SQL
    externalDocs:
      description: Fluxo SQL
      url: https://mermaid.live/view#pako:eNptkd9OwjAUxl-lOTfcABmjbDISDYr8UaJEiBcyLsp6hMatJV2XiMDT-Ci-mN0AnYl37dfv950vPTuIFEcIYKXZZk1mvU4o02x5vIXQj7N3FZDHpUFNxiI1jHAkE614ZlQaQigJ6fbnN7FAaXBBarXL_VTFIhLWGZ_9m5N_T7qDeXcyWnQKblDYn1GLVxExIhlZshRzgDNeuIfzayYjlUu9XDqBwwKcYfKTfGXNox05HN9Hxx4isepdaeBdoT-hUdoOK7Xql7mHr09ltfsSeP8HTFCmbGWnV6alCpXfnGO_W62L5pGyPxobZt_Hpczx_5kWwBykDj0FouShhCokqBMmuN3VLg8IwawxwRACe-RMv-XbOFgfs22mWxlBYHSGVcg2nBnsCWaXmpzFDZMvSpWvEOzgHYKmV3eo6zWp16au23AaVdhC4NVbDvUdr-H6Dr1wLhqHKnwUvFP3fc9vuq7XatO2S9vNwzfCvr1W

paths:
  /api/faturas:
    post:
      tags:
      - Microserviços
      summary: Criar uma nova fatura
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                cliente_id:
                  type: number
                valor:
                  type: number
                descricao:
                  type: string
              required:
                - cliente_id
                - valor
      responses:
        '201':
          description: Fatura criada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  numero_fatura:
                    type: string
                  status:
                    type: string
                    enum: [criada, paga, cancelada]
              example:
                numero_fatura: "12345"
                status: "criada"
        '400':
          description: Cliente inválido fornecido
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: "Cliente fornecido é inválido"

  /api/faturas/{numero_fatura}:
    get:
      tags:
      - Microserviços
      summary: Obter detalhes de uma fatura
      parameters:
        - name: numero_fatura
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Detalhes da fatura recuperados com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  numero_fatura:
                    type: string
                  valor:
                    type: number
                  descricao:
                    type: string
                  nome_cliente:
                    type: string
              example:
                numero_fatura: "12345"
                valor: 100.0
                descricao: "Serviços de energia"
                nome_cliente: "Cliente Exemplo"
        '404':
          description: Fatura não encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: "Fatura não encontrada"

  /api/faturas/{numero_fatura}/pagamento:
    post:
      tags:
      - Microserviços
      summary: Processar pagamento de uma fatura
      parameters:
        - name: numero_fatura
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                forma_pagamento:
                  type: string
                numero_cartao:
                  type: string
                valor:
                  type: number
              required:
                - forma_pagamento
                - numero_cartao
                - valor
      responses:
        '200':
          description: Pagamento processado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: "Pagamento processado com sucesso"
        '401':
          description: Pagamento não autorizado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: "Pagamento não autorizado"

  /api/produtos/:
    get:
      tags:
      - Banco de Dados
      summary: Retorna os produtos existentes na base
      responses:
        '200':
          description: Lista de produtos e serviços recuperada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      type: object
                      properties:
                        product_id:
                          type: string
                        name:
                          type: string
              example:
                products:
                  - product_id: "1"
                    name: "Energia Elétrica"
                  - product_id: "2"
                    name: "Manutenção de Equipamentos"
        '404':
          description: Produto não encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: "Produto não encontrado"
